PUT http://localhost:8080/api/clientes/atualizar-parcial/{{id}}
Content-Type: application/json

{
  "cpf": "82328490026",
  "nome": "Teste1",
  "email": "teste.teste1@gmail.com",
  "telefone": "11911645103"
}